table Geography
	lineageTag: b83f3b23-7239-4237-970c-5ccf6b7924a1

	column Zip
		dataType: string
		lineageTag: 2911c194-88be-4a32-aca3-b83f463b78a4
		summarizeBy: none
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: a378de14-9fac-428c-b5f7-6cd852902685
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 909b9a9d-d270-429d-a3ce-090381d8b687
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f8e7728f-4e1c-4504-abf9-668675894e61
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: ca064b19-5643-478c-bacc-72f700778278
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: f8caf598-7cca-4873-aa4f-3ac588a3391c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Country_Zip
		dataType: string
		isHidden
		lineageTag: f78d722f-b327-4cf2-b0a1-639465537267
		summarizeBy: none
		sourceColumn: Country_Zip

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Geography = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\brcampb\OneDrive - Microsoft\DIAD\Data\USSales\bi_dimensions.xlsx"), null, true),
				    geo_Sheet = Source{[Item="geo",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(geo_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Source:", type text}, {"Public Database ", type any}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",2),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Zip", type text}, {"City", type text}, {"State", type text}, {"Region", type text}, {"District", type text}, {"Country", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "CountryZip", each [Country] & " " & [Zip]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"CountryZip", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"CountryZip", "Country_Zip"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

