table Manufacturer
	lineageTag: d2a312fa-a009-4342-afe9-f3f354151e13

	column ManufacturerID
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: c1b85aa6-fa36-46cc-b479-97f923d54c85
		summarizeBy: none
		sourceColumn: ManufacturerID

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: 486cc604-5db7-4bf4-baaf-1439c96709f3
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		lineageTag: 9c04a318-b1c9-415f-82f4-1174adb4063c
		summarizeBy: none
		sourceColumn: Logo

		annotation SummarizationSetBy = Automatic

	partition Manufacturer = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\brcampb\OneDrive - Microsoft\DIAD\Data\USSales\bi_dimensions.xlsx"), null, true),
				    manufacturer_Sheet = Source{[Item="manufacturer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(manufacturer_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type",3),
				    #"Transposed Table" = Table.Transpose(#"Removed Bottom Rows"),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"ManufacturerID", Int64.Type}, {"Manufacturer", type text}, {"Logo", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

