table Product
	lineageTag: 66e67c63-aa12-421a-ab7d-38796ee3bd15

	column ProductID
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: f1bf077e-1aca-49f8-9f45-ce3a128332c0
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 5e20c5ab-6d0c-42ff-8143-25de8c0f95db
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: e80fe8d9-d5c2-46c2-8a5b-27602ea526b7
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 2e21d972-89cb-41d2-b0df-f179d7b7ddb0
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column ManufacturerID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 15a6cf1e-341c-45ea-98bf-9db4576cb759
		summarizeBy: none
		sourceColumn: ManufacturerID

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 4abf83d5-8f5d-463f-9b7d-bdb0cf432878
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column MSRP
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e2e37480-83d4-4ce6-87ad-8ef0d1554f0a
		summarizeBy: sum
		sourceColumn: MSRP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	hierarchy 'Product Hierarchy'
		lineageTag: ae859687-1e3a-4068-9c93-93be9afd2ff1

		level Category
			lineageTag: fc5d3b7d-ab6a-495c-8789-9b1414bd86c1
			column: Category

		level Segment
			lineageTag: 73f4089e-a354-4c8c-a714-a8919e3a897b
			column: Segment

		level Product
			lineageTag: 9164521f-2c75-480f-8115-cdc49b3ddb42
			column: Product

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\brcampb\OneDrive - Microsoft\DIAD\Data\USSales\bi_dimensions.xlsx"), null, true),
				    Product_Table_Table = Source{[Item="Product_Table",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Product_Table_Table,{{"ProductID", Int64.Type}, {"Product", type text}, {"Category", type text}, {"ManufacturerID", Int64.Type}, {"Price", type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Product", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"Product.1", "Product.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Product.1", type text}, {"Product.2", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Product.1", "Product"}, {"Product.2", "Segment"}}),
				    #"Filled Down" = Table.FillDown(#"Renamed Columns",{"Category"}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Filled Down", "Price", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Price.1", "Price.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Price.1", type text}, {"Price.2", type number}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"Price.1", "Currency"}, {"Price.2", "MSRP"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"MSRP", Currency.Type}})
				in
				    #"Changed Type3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

