table Sales
	lineageTag: 2ad3f09e-7e0d-4bae-8daa-52ffcef5d3a2

	column ProductID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 89c65e44-d88a-457c-8666-a5ec9bf3afc2
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 9b1f054d-9f33-4f1f-ab6f-552ee69af55e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Zip
		dataType: string
		lineageTag: 4982e1b6-6177-4b80-90ad-4cec5cf72b82
		summarizeBy: none
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		formatString: 0
		lineageTag: 69898208-081f-4864-8b3f-7d91f6ff5817
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1d610b4c-8d8f-4f7e-9b91-471f48012683
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Country
		dataType: string
		lineageTag: ddb28507-ebcf-406b-b567-af613d7d3744
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Country_Zip
		dataType: string
		isHidden
		lineageTag: eeceb273-c5c9-495a-b401-0d6f9dc01446
		summarizeBy: none
		sourceColumn: Country_Zip

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\brcampb\OneDrive - Microsoft\DIAD\Data\USSales\sales.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", Int64.Type}, {"Date", type date}, {"Zip", type text}, {"Units", Int64.Type}, {"Revenue", type number}}),
				    #"Appended Query" = Table.Combine({#"Changed Type", #"International Sales"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Appended Query", "CountryName", each if [Country] = null then "USA" else [Country]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"Country"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"CountryName", "Country"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Country", type text}, {"Revenue", Currency.Type}, {"Zip", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "CountryZip", each [Country] & " " & [Zip]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"CountryZip", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"CountryZip", "Country_Zip"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

